/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy):  6.10.2025   Time (hh:mm): 13:04                        */
/*******************************************************************************/


#include "gx_api.h"
#include "power_supply_resources.h"

/* Color Table                                                                 */

GX_CONST GX_COLOR display_1_theme_1_color_table[] =
{
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000
};


/* Font THEME_1_tips Data Definition                                           */

static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_20[1] =
{
    0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_21[10] =
{
    0xc0, 0xc0, 0x80, 0x80, 0x80, 0x80, 0x80, 0x00, 0xc0, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_22[4] =
{
    0x90, 0x90, 0x90, 0x90
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_23[20] =
{
    0x09, 0x00, 0x09, 0x00, 0x19, 0x00, 0x7f, 0xc0, 0x12, 0x00, 0x12, 0x00, 0xff, 
    0x80, 0x24, 0x00, 0x24, 0x00, 0x24, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_24[13] =
{
    0x10, 0x10, 0x78, 0xd4, 0xd4, 0xd0, 0x38, 0x16, 0x96, 0xd6, 0x7c, 0x10, 0x10

};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_25[20] =
{
    0x70, 0x80, 0x91, 0x00, 0x91, 0x00, 0x92, 0x00, 0x94, 0xe0, 0x75, 0x20, 0x09, 
    0x30, 0x09, 0x30, 0x11, 0x20, 0x20, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_26[20] =
{
    0x3c, 0x00, 0x22, 0x00, 0x62, 0x00, 0x30, 0x00, 0x59, 0xe0, 0xcc, 0x80, 0x86, 
    0x80, 0xc3, 0x00, 0xc3, 0x80, 0x3c, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_27[4] =
{
    0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_28[13] =
{
    0x20, 0x20, 0x40, 0x40, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0x40, 0x40, 0x20, 0x20

};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_29[13] =
{
    0x80, 0x40, 0x60, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x60, 0x40, 0x80

};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_2a[6] =
{
    0x10, 0xd6, 0x38, 0x38, 0xd6, 0x10
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_2b[18] =
{
    0x08, 0x00, 0x08, 0x00, 0x08, 0x00, 0x08, 0x00, 0xff, 0x80, 0x08, 0x00, 0x08, 
    0x00, 0x08, 0x00, 0x08, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_2c[3] =
{
    0x20, 0x60, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_2d[1] =
{
    0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_2e[2] =
{
    0xc0, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_2f[12] =
{
    0x18, 0x10, 0x10, 0x10, 0x20, 0x20, 0x20, 0x40, 0x40, 0x40, 0xc0, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_30[10] =
{
    0x38, 0x44, 0xc6, 0x86, 0x82, 0x82, 0x86, 0xc6, 0x44, 0x38
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_31[10] =
{
    0x20, 0xe0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xf8
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_32[10] =
{
    0x78, 0x8c, 0x84, 0x04, 0x04, 0x08, 0x10, 0x20, 0x42, 0xfe
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_33[10] =
{
    0x78, 0xc4, 0x84, 0x04, 0x38, 0x04, 0x06, 0x86, 0xc6, 0x7c
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_34[10] =
{
    0x04, 0x0c, 0x14, 0x24, 0x24, 0x44, 0xff, 0x04, 0x04, 0x1f
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_35[10] =
{
    0x7c, 0x80, 0x80, 0xb8, 0x44, 0x06, 0x06, 0x86, 0xc4, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_36[10] =
{
    0x3c, 0x46, 0xc2, 0xbc, 0xc6, 0xc6, 0xc2, 0xc6, 0x46, 0x3c
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_37[10] =
{
    0xfe, 0x86, 0x04, 0x04, 0x08, 0x08, 0x10, 0x10, 0x10, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_38[10] =
{
    0x7c, 0xc4, 0xc6, 0x44, 0x38, 0xc4, 0x86, 0x86, 0xc6, 0x7c
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_39[10] =
{
    0x78, 0xc4, 0x86, 0x86, 0x86, 0xc6, 0x7e, 0x86, 0xc4, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_3a[6] =
{
    0x40, 0x40, 0x00, 0x00, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_3b[7] =
{
    0x20, 0x20, 0x00, 0x00, 0x20, 0x60, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_3c[16] =
{
    0x00, 0x80, 0x07, 0x80, 0x1c, 0x00, 0xe0, 0x00, 0xe0, 0x00, 0x1c, 0x00, 0x07, 
    0x80, 0x00, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_3d[8] =
{
    0xff, 0x80, 0x00, 0x00, 0x00, 0x00, 0xff, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_3e[16] =
{
    0xc0, 0x00, 0x70, 0x00, 0x0e, 0x00, 0x03, 0x80, 0x03, 0x80, 0x0e, 0x00, 0x70, 
    0x00, 0xc0, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_3f[10] =
{
    0x78, 0x8c, 0x8c, 0x0c, 0x18, 0x30, 0x20, 0x00, 0x20, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_40[24] =
{
    0x0f, 0x80, 0x30, 0x40, 0x40, 0x20, 0xce, 0x90, 0x99, 0x90, 0x90, 0x90, 0x90, 
    0x90, 0x99, 0xa0, 0xce, 0xc0, 0x40, 0x00, 0x30, 0x40, 0x0f, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_41[20] =
{
    0x0c, 0x00, 0x0c, 0x00, 0x16, 0x00, 0x16, 0x00, 0x22, 0x00, 0x23, 0x00, 0x3f, 
    0x00, 0x41, 0x80, 0x41, 0x80, 0xe1, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_42[10] =
{
    0xfe, 0x43, 0x43, 0x43, 0x7c, 0x43, 0x41, 0x41, 0x43, 0xfe
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_43[20] =
{
    0x3e, 0x00, 0x61, 0x80, 0xc0, 0x80, 0xc0, 0x00, 0x80, 0x00, 0x80, 0x00, 0xc0, 
    0x00, 0xc1, 0x80, 0x61, 0x00, 0x3e, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_44[20] =
{
    0xfe, 0x00, 0x43, 0x00, 0x41, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 
    0x80, 0x41, 0x80, 0x43, 0x00, 0xfe, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_45[10] =
{
    0xff, 0x41, 0x40, 0x42, 0x7e, 0x42, 0x40, 0x40, 0x41, 0xff
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_46[10] =
{
    0xff, 0x41, 0x40, 0x42, 0x7e, 0x42, 0x40, 0x40, 0x40, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_47[20] =
{
    0x3f, 0x00, 0x61, 0x80, 0xc0, 0x80, 0xc0, 0x00, 0x80, 0x00, 0x83, 0x80, 0xc0, 
    0x80, 0xc0, 0x80, 0x61, 0x80, 0x3f, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_48[20] =
{
    0xf3, 0xc0, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x7f, 0x80, 0x40, 0x80, 0x40, 
    0x80, 0x40, 0x80, 0x40, 0x80, 0xf3, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_49[10] =
{
    0xf0, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_4a[13] =
{
    0x3c, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x18, 0x98, 0x90, 0xf0

};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_4b[20] =
{
    0xf3, 0x80, 0x42, 0x00, 0x44, 0x00, 0x48, 0x00, 0x70, 0x00, 0x58, 0x00, 0x4c, 
    0x00, 0x46, 0x00, 0x43, 0x00, 0xf1, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_4c[10] =
{
    0xf0, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x41, 0x41, 0xff
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_4d[20] =
{
    0xe0, 0x38, 0x60, 0x60, 0x70, 0xa0, 0x50, 0xa0, 0x59, 0x20, 0x49, 0x20, 0x4e, 
    0x20, 0x46, 0x20, 0x40, 0x20, 0xe0, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_4e[20] =
{
    0xe1, 0xe0, 0x70, 0x80, 0x70, 0x80, 0x58, 0x80, 0x4c, 0x80, 0x46, 0x80, 0x42, 
    0x80, 0x43, 0x80, 0x41, 0x80, 0xe0, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_4f[20] =
{
    0x3e, 0x00, 0x61, 0x00, 0xc0, 0x80, 0xc0, 0xc0, 0x80, 0xc0, 0x80, 0xc0, 0xc0, 
    0xc0, 0xc0, 0x80, 0x61, 0x00, 0x3e, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_50[10] =
{
    0xfe, 0x43, 0x43, 0x43, 0x43, 0x7e, 0x40, 0x40, 0x40, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_51[24] =
{
    0x3e, 0x00, 0x61, 0x00, 0xc0, 0x80, 0xc0, 0xc0, 0x80, 0xc0, 0x80, 0xc0, 0xc0, 
    0xc0, 0xc0, 0x80, 0x61, 0x00, 0x3e, 0x00, 0x04, 0x00, 0x03, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_52[20] =
{
    0xfe, 0x00, 0x43, 0x00, 0x43, 0x00, 0x43, 0x00, 0x43, 0x00, 0x7c, 0x00, 0x46, 
    0x00, 0x43, 0x00, 0x41, 0x00, 0xf1, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_53[10] =
{
    0x7c, 0xc2, 0xc2, 0xc0, 0x70, 0x1e, 0x02, 0x83, 0xc2, 0x7c
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_54[20] =
{
    0xff, 0x80, 0x88, 0x80, 0x88, 0x80, 0x08, 0x00, 0x08, 0x00, 0x08, 0x00, 0x08, 
    0x00, 0x08, 0x00, 0x08, 0x00, 0x1e, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_55[20] =
{
    0xf1, 0xc0, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 
    0x80, 0x60, 0x80, 0x61, 0x00, 0x3e, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_56[20] =
{
    0xf1, 0xc0, 0x60, 0x80, 0x60, 0x80, 0x21, 0x00, 0x31, 0x00, 0x11, 0x00, 0x1a, 
    0x00, 0x1a, 0x00, 0x0c, 0x00, 0x0c, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_57[20] =
{
    0xf1, 0x1c, 0x61, 0x88, 0x23, 0x88, 0x22, 0x88, 0x32, 0x90, 0x34, 0xd0, 0x14, 
    0x50, 0x14, 0x60, 0x18, 0x60, 0x08, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_58[20] =
{
    0xf3, 0x80, 0x21, 0x00, 0x32, 0x00, 0x1c, 0x00, 0x0c, 0x00, 0x0c, 0x00, 0x16, 
    0x00, 0x23, 0x00, 0x21, 0x00, 0xe3, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_59[20] =
{
    0xf3, 0x80, 0x61, 0x00, 0x22, 0x00, 0x32, 0x00, 0x1c, 0x00, 0x08, 0x00, 0x08, 
    0x00, 0x08, 0x00, 0x08, 0x00, 0x1e, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_5a[10] =
{
    0xff, 0x82, 0x84, 0x0c, 0x18, 0x10, 0x20, 0x60, 0xc1, 0xff
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_5b[12] =
{
    0xe0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xc0, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_5c[12] =
{
    0x80, 0xc0, 0x40, 0x40, 0x40, 0x20, 0x20, 0x20, 0x10, 0x10, 0x10, 0x18
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_5d[12] =
{
    0xe0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_5e[8] =
{
    0x0c, 0x00, 0x1e, 0x00, 0x23, 0x00, 0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_5f[1] =
{
    0xfe
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_60[3] =
{
    0x40, 0x40, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_61[8] =
{
    0x78, 0x8c, 0x04, 0x7c, 0x84, 0x84, 0x8c, 0x76
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_62[11] =
{
    0xe0, 0x20, 0x20, 0x2e, 0x33, 0x21, 0x21, 0x21, 0x21, 0x33, 0xee
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_63[8] =
{
    0x78, 0xc4, 0x80, 0x80, 0x80, 0x80, 0xc4, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_64[11] =
{
    0x0c, 0x04, 0x04, 0x74, 0xcc, 0x84, 0x84, 0x84, 0x84, 0xcc, 0x77
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_65[8] =
{
    0x78, 0xc4, 0x84, 0xfe, 0x80, 0x80, 0xc4, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_66[11] =
{
    0x3c, 0x20, 0x20, 0xf8, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xf8
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_67[11] =
{
    0x77, 0xcc, 0x84, 0x84, 0x84, 0x84, 0xcc, 0x74, 0x04, 0x8c, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_68[22] =
{
    0xe0, 0x00, 0x20, 0x00, 0x20, 0x00, 0x2e, 0x00, 0x32, 0x00, 0x22, 0x00, 0x23, 
    0x00, 0x23, 0x00, 0x23, 0x00, 0x23, 0x00, 0x77, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_69[11] =
{
    0x60, 0x60, 0x00, 0xe0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_6a[14] =
{
    0x10, 0x10, 0x00, 0x30, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x90, 
    0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_6b[22] =
{
    0xe0, 0x00, 0x20, 0x00, 0x20, 0x00, 0x27, 0x00, 0x24, 0x00, 0x28, 0x00, 0x38, 
    0x00, 0x2c, 0x00, 0x24, 0x00, 0x22, 0x00, 0xf7, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_6c[11] =
{
    0xe0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_6d[16] =
{
    0xee, 0xe0, 0x33, 0x30, 0x22, 0x30, 0x22, 0x30, 0x22, 0x30, 0x22, 0x30, 0x22, 
    0x30, 0x77, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_6e[16] =
{
    0xee, 0x00, 0x32, 0x00, 0x22, 0x00, 0x23, 0x00, 0x23, 0x00, 0x23, 0x00, 0x23, 
    0x00, 0x77, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_6f[8] =
{
    0x78, 0xc4, 0x86, 0x86, 0x86, 0x86, 0xc4, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_70[11] =
{
    0xee, 0x33, 0x21, 0x21, 0x21, 0x21, 0x33, 0x2e, 0x20, 0x20, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_71[11] =
{
    0x77, 0xcc, 0x84, 0x84, 0x84, 0x84, 0xcc, 0x74, 0x04, 0x04, 0x0f
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_72[8] =
{
    0xee, 0x32, 0x20, 0x20, 0x20, 0x20, 0x20, 0x70
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_73[8] =
{
    0x70, 0x88, 0x80, 0xe0, 0x38, 0x08, 0x88, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_74[10] =
{
    0x20, 0x20, 0xf8, 0x20, 0x20, 0x20, 0x20, 0x20, 0x28, 0x38
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_75[16] =
{
    0xe6, 0x00, 0x22, 0x00, 0x22, 0x00, 0x22, 0x00, 0x22, 0x00, 0x22, 0x00, 0x26, 
    0x00, 0x3b, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_76[8] =
{
    0xe7, 0x42, 0x64, 0x24, 0x24, 0x38, 0x18, 0x18
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_77[16] =
{
    0xf2, 0x70, 0x46, 0x20, 0x26, 0x20, 0x27, 0x40, 0x29, 0x40, 0x39, 0x40, 0x19, 
    0x80, 0x10, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_78[8] =
{
    0xe6, 0x64, 0x38, 0x18, 0x18, 0x2c, 0x44, 0xef
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_79[11] =
{
    0xe7, 0x42, 0x62, 0x24, 0x24, 0x38, 0x18, 0x18, 0x10, 0x10, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_7a[8] =
{
    0xfc, 0x88, 0x10, 0x30, 0x20, 0x40, 0xc4, 0xfc
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_7b[13] =
{
    0x38, 0x20, 0x20, 0x20, 0x20, 0x20, 0xc0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x38

};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_7c[14] =
{
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 
    0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_7d[13] =
{
    0xc0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x18, 0x20, 0x20, 0x20, 0x20, 0x20, 0xe0

};
static GX_CONST GX_UBYTE FONT_THEME_1_tips_char_7e[4] =
{
    0x78, 0x80, 0x87, 0x00
};
static GX_CONST GX_GLYPH THEME_1_tips_FONT_PAGE_1_GLYPHS[95] =
{
    {FONT_THEME_1_tips_char_20, 0, 0, 4, 0, 1, 1},
    {FONT_THEME_1_tips_char_21, 10, 0, 6, 1, 2, 10},
    {FONT_THEME_1_tips_char_22, 10, -6, 6, 1, 4, 4},
    {FONT_THEME_1_tips_char_23, 10, 0, 12, 1, 10, 10},
    {FONT_THEME_1_tips_char_24, 11, 2, 9, 1, 7, 13},
    {FONT_THEME_1_tips_char_25, 10, 0, 13, 0, 12, 10},
    {FONT_THEME_1_tips_char_26, 10, 0, 12, 1, 11, 10},
    {FONT_THEME_1_tips_char_27, 10, -6, 4, 1, 1, 4},
    {FONT_THEME_1_tips_char_28, 11, 2, 5, 1, 3, 13},
    {FONT_THEME_1_tips_char_29, 11, 2, 5, 0, 3, 13},
    {FONT_THEME_1_tips_char_2a, 10, -4, 7, 0, 7, 6},
    {FONT_THEME_1_tips_char_2b, 9, 0, 12, 1, 9, 9},
    {FONT_THEME_1_tips_char_2c, 2, 1, 4, 0, 3, 3},
    {FONT_THEME_1_tips_char_2d, 4, -3, 5, 0, 3, 1},
    {FONT_THEME_1_tips_char_2e, 2, 0, 4, 1, 2, 2},
    {FONT_THEME_1_tips_char_2f, 10, 2, 5, 0, 5, 12},
    {FONT_THEME_1_tips_char_30, 10, 0, 9, 0, 7, 10},
    {FONT_THEME_1_tips_char_31, 10, 0, 9, 1, 5, 10},
    {FONT_THEME_1_tips_char_32, 10, 0, 9, 0, 7, 10},
    {FONT_THEME_1_tips_char_33, 10, 0, 9, 1, 7, 10},
    {FONT_THEME_1_tips_char_34, 10, 0, 9, 0, 8, 10},
    {FONT_THEME_1_tips_char_35, 10, 0, 9, 1, 7, 10},
    {FONT_THEME_1_tips_char_36, 10, 0, 9, 0, 7, 10},
    {FONT_THEME_1_tips_char_37, 10, 0, 9, 1, 7, 10},
    {FONT_THEME_1_tips_char_38, 10, 0, 9, 0, 7, 10},
    {FONT_THEME_1_tips_char_39, 10, 0, 9, 0, 7, 10},
    {FONT_THEME_1_tips_char_3a, 6, 0, 5, 1, 2, 6},
    {FONT_THEME_1_tips_char_3b, 6, 1, 5, 0, 3, 7},
    {FONT_THEME_1_tips_char_3c, 8, 0, 12, 1, 9, 8},
    {FONT_THEME_1_tips_char_3d, 7, -3, 12, 1, 9, 4},
    {FONT_THEME_1_tips_char_3e, 8, 0, 12, 1, 9, 8},
    {FONT_THEME_1_tips_char_3f, 10, 0, 8, 0, 6, 10},
    {FONT_THEME_1_tips_char_40, 10, 2, 14, 0, 12, 12},
    {FONT_THEME_1_tips_char_41, 10, 0, 10, -1, 10, 10},
    {FONT_THEME_1_tips_char_42, 10, 0, 10, 0, 8, 10},
    {FONT_THEME_1_tips_char_43, 10, 0, 11, 0, 9, 10},
    {FONT_THEME_1_tips_char_44, 10, 0, 11, 0, 9, 10},
    {FONT_THEME_1_tips_char_45, 10, 0, 10, 0, 8, 10},
    {FONT_THEME_1_tips_char_46, 10, 0, 10, 0, 8, 10},
    {FONT_THEME_1_tips_char_47, 10, 0, 11, 0, 9, 10},
    {FONT_THEME_1_tips_char_48, 10, 0, 12, 0, 10, 10},
    {FONT_THEME_1_tips_char_49, 10, 0, 6, 0, 4, 10},
    {FONT_THEME_1_tips_char_4a, 10, 3, 6, -2, 6, 13},
    {FONT_THEME_1_tips_char_4b, 10, 0, 10, 0, 10, 10},
    {FONT_THEME_1_tips_char_4c, 10, 0, 9, 0, 8, 10},
    {FONT_THEME_1_tips_char_4d, 10, 0, 14, 0, 13, 10},
    {FONT_THEME_1_tips_char_4e, 10, 0, 12, 0, 11, 10},
    {FONT_THEME_1_tips_char_4f, 10, 0, 11, 0, 10, 10},
    {FONT_THEME_1_tips_char_50, 10, 0, 9, 0, 8, 10},
    {FONT_THEME_1_tips_char_51, 10, 2, 11, 0, 10, 12},
    {FONT_THEME_1_tips_char_52, 10, 0, 11, 0, 10, 10},
    {FONT_THEME_1_tips_char_53, 10, 0, 10, 1, 8, 10},
    {FONT_THEME_1_tips_char_54, 10, 0, 9, 0, 9, 10},
    {FONT_THEME_1_tips_char_55, 10, 0, 12, 0, 10, 10},
    {FONT_THEME_1_tips_char_56, 10, 0, 10, -1, 10, 10},
    {FONT_THEME_1_tips_char_57, 10, 0, 14, 0, 14, 10},
    {FONT_THEME_1_tips_char_58, 10, 0, 10, 0, 10, 10},
    {FONT_THEME_1_tips_char_59, 10, 0, 9, -1, 9, 10},
    {FONT_THEME_1_tips_char_5a, 10, 0, 10, 0, 8, 10},
    {FONT_THEME_1_tips_char_5b, 11, 1, 5, 1, 3, 12},
    {FONT_THEME_1_tips_char_5c, 10, 2, 5, 0, 5, 12},
    {FONT_THEME_1_tips_char_5d, 11, 1, 5, 1, 3, 12},
    {FONT_THEME_1_tips_char_5e, 10, -6, 12, 1, 9, 4},
    {FONT_THEME_1_tips_char_5f, -2, 3, 7, 0, 7, 1},
    {FONT_THEME_1_tips_char_60, 11, -8, 7, 1, 3, 3},
    {FONT_THEME_1_tips_char_61, 8, 0, 8, 0, 7, 8},
    {FONT_THEME_1_tips_char_62, 11, 0, 9, 0, 8, 11},
    {FONT_THEME_1_tips_char_63, 8, 0, 8, 0, 6, 8},
    {FONT_THEME_1_tips_char_64, 11, 0, 9, 0, 8, 11},
    {FONT_THEME_1_tips_char_65, 8, 0, 8, 0, 7, 8},
    {FONT_THEME_1_tips_char_66, 11, 0, 5, 0, 6, 11},
    {FONT_THEME_1_tips_char_67, 8, 3, 9, 0, 8, 11},
    {FONT_THEME_1_tips_char_68, 11, 0, 9, 0, 9, 11},
    {FONT_THEME_1_tips_char_69, 11, 0, 4, 0, 4, 11},
    {FONT_THEME_1_tips_char_6a, 11, 3, 4, -2, 4, 14},
    {FONT_THEME_1_tips_char_6b, 11, 0, 8, 0, 9, 11},
    {FONT_THEME_1_tips_char_6c, 11, 0, 4, 0, 4, 11},
    {FONT_THEME_1_tips_char_6d, 8, 0, 13, 0, 13, 8},
    {FONT_THEME_1_tips_char_6e, 8, 0, 9, 0, 9, 8},
    {FONT_THEME_1_tips_char_6f, 8, 0, 8, 0, 7, 8},
    {FONT_THEME_1_tips_char_70, 8, 3, 9, 0, 8, 11},
    {FONT_THEME_1_tips_char_71, 8, 3, 9, 0, 8, 11},
    {FONT_THEME_1_tips_char_72, 8, 0, 7, 0, 7, 8},
    {FONT_THEME_1_tips_char_73, 8, 0, 7, 0, 5, 8},
    {FONT_THEME_1_tips_char_74, 10, 0, 6, 0, 6, 10},
    {FONT_THEME_1_tips_char_75, 8, 0, 9, 0, 9, 8},
    {FONT_THEME_1_tips_char_76, 8, 0, 8, -1, 8, 8},
    {FONT_THEME_1_tips_char_77, 8, 0, 12, 0, 12, 8},
    {FONT_THEME_1_tips_char_78, 8, 0, 8, 0, 8, 8},
    {FONT_THEME_1_tips_char_79, 8, 3, 8, -1, 8, 11},
    {FONT_THEME_1_tips_char_7a, 8, 0, 7, 0, 6, 8},
    {FONT_THEME_1_tips_char_7b, 11, 2, 9, 1, 5, 13},
    {FONT_THEME_1_tips_char_7c, 11, 3, 5, 1, 1, 14},
    {FONT_THEME_1_tips_char_7d, 11, 2, 9, 1, 5, 13},
    {FONT_THEME_1_tips_char_7e, 6, -2, 12, 1, 9, 2}
};

static GX_CONST GX_FONT THEME_1_tips = 
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    14,                                      /* font data height               */
    11,                                      /* font baseline offset           */
    0x20,                                    /* first glyph within data page   */
    0x7e,                                    /* last glyph within data page    */
    {THEME_1_tips_FONT_PAGE_1_GLYPHS},       /* pointer to glyph data          */
    GX_NULL                                  /* next font page                 */
};


/* Font THEME_1_YaHei Data Definition                                          */

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_8f93[28] =
{
    0x20, 0x40, 0x20, 0xc0, 0xf9, 0x20, 0x47, 0xf8, 0x40, 0x00, 0x47, 0x80, 0x54, 
    0xa8, 0x7c, 0xa8, 0x17, 0xa8, 0x14, 0xa8, 0x7f, 0xa8, 0x14, 0xa8, 0x14, 0x88, 
    0x15, 0xb8
};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_12_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_8f93, 12, 2, 14, 0, 14, 14}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_12 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x8f93,                                  /* first glyph within data page   */
    0x8f93,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_12_GLYPHS},     /* pointer to glyph data          */
    GX_NULL                                  /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_8bbe[26] =
{
    0x43, 0xf0, 0x22, 0x10, 0x12, 0x10, 0x02, 0x1c, 0xec, 0x00, 0x27, 0xf0, 0x22, 
    0x10, 0x22, 0x20, 0x21, 0x20, 0x31, 0xc0, 0x21, 0xc0, 0x07, 0x30, 0x08, 0x08

};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_11_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_8bbe, 11, 2, 14, 0, 14, 13}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_11 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x8bbe,                                  /* first glyph within data page   */
    0x8bbe,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_11_GLYPHS},     /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_12                   /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_7f6e[24] =
{
    0x3f, 0xf0, 0x44, 0x88, 0x3f, 0xf0, 0x7f, 0xf8, 0x02, 0x00, 0x3f, 0xf0, 0x3f, 
    0xf0, 0x20, 0x10, 0x3f, 0xf0, 0x3f, 0xf0, 0x20, 0x10, 0xff, 0xfc
};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_10_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_7f6e, 11, 1, 14, 0, 14, 12}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_10 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x7f6e,                                  /* first glyph within data page   */
    0x7f6e,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_10_GLYPHS},     /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_11                   /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_7535[24] =
{
    0x04, 0x00, 0xff, 0xe0, 0x84, 0x20, 0x84, 0x20, 0x84, 0x20, 0xff, 0xe0, 0x84, 
    0x20, 0x84, 0x20, 0xff, 0xe0, 0x84, 0x08, 0x04, 0x10, 0x07, 0xf0
};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_9_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_7535, 11, 2, 14, 1, 13, 12}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_9 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x7535,                                  /* first glyph within data page   */
    0x7535,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_9_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_10                   /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6d41[28] =
{
    0x00, 0x80, 0x40, 0x80, 0x2f, 0xf8, 0x01, 0x00, 0x02, 0x20, 0x44, 0x10, 0x2f, 
    0xf0, 0x00, 0x08, 0x04, 0xa0, 0x24, 0xa0, 0x24, 0xa0, 0x44, 0xa4, 0x48, 0xa4, 
    0x50, 0x98
};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_8_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_6d41, 12, 3, 14, 0, 14, 14}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_8 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x6d41,                                  /* first glyph within data page   */
    0x6d41,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_8_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_9                    /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6700[26] =
{
    0x3f, 0xf0, 0x20, 0x10, 0x3f, 0xf0, 0x3f, 0xf0, 0x00, 0x00, 0xff, 0xfc, 0x22, 
    0x00, 0x3f, 0xf8, 0x22, 0x88, 0x3e, 0x90, 0x22, 0x60, 0x7e, 0x50, 0x03, 0x88

};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_7_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_6700, 11, 2, 14, 0, 14, 13}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_7 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x6700,                                  /* first glyph within data page   */
    0x6700,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_7_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_8                    /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5927[26] =
{
    0x02, 0x00, 0x02, 0x00, 0x02, 0x00, 0xff, 0xf0, 0x04, 0x00, 0x06, 0x00, 0x06, 
    0x00, 0x05, 0x00, 0x09, 0x00, 0x10, 0x80, 0x30, 0x40, 0x40, 0x30, 0x80, 0x10

};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_6_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_5927, 11, 2, 14, 0, 13, 13}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_6 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x5927,                                  /* first glyph within data page   */
    0x5927,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_6_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_7                    /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_538b[26] =
{
    0x3f, 0xf8, 0x20, 0x00, 0x20, 0x80, 0x20, 0x80, 0x20, 0x80, 0x2f, 0xf8, 0x20, 
    0x80, 0x20, 0xa0, 0x20, 0x90, 0x20, 0x88, 0x40, 0x80, 0x5f, 0xfc, 0x80, 0x00

};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_5_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_538b, 11, 2, 14, 0, 14, 13}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_5 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x538b,                                  /* first glyph within data page   */
    0x538b,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_5_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_6                    /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_51fa[24] =
{
    0x44, 0x20, 0x44, 0x20, 0x44, 0x20, 0x44, 0x20, 0x7f, 0xe0, 0x04, 0x00, 0x04, 
    0x00, 0x84, 0x10, 0x84, 0x10, 0x84, 0x10, 0x84, 0x10, 0xff, 0xf0
};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_4_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_51fa, 11, 1, 14, 1, 12, 12}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_4 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x51fa,                                  /* first glyph within data page   */
    0x51fa,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_4_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_5                    /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5165[24] =
{
    0x08, 0x00, 0x04, 0x00, 0x02, 0x00, 0x03, 0x00, 0x03, 0x00, 0x04, 0x80, 0x04, 
    0x80, 0x08, 0x40, 0x10, 0x20, 0x10, 0x20, 0x20, 0x18, 0x40, 0x08
};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_3_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_5165, 11, 1, 14, 0, 14, 12}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_3 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x5165,                                  /* first glyph within data page   */
    0x5165,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_3_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_4                    /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_4f0f[26] =
{
    0x10, 0x80, 0x10, 0x90, 0x10, 0x88, 0x20, 0x80, 0x2f, 0xfc, 0x60, 0x80, 0xa0, 
    0x80, 0x20, 0xc0, 0x21, 0x40, 0x21, 0x20, 0x22, 0x20, 0x24, 0x18, 0x28, 0x00

};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_2_GLYPHS[1] =
{
    {FONT_THEME_1_YaHei_char_4f0f, 11, 2, 14, 0, 14, 13}
};

static GX_CONST GX_FONT THEME_1_YaHei_PAGE_2 =
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x4f0f,                                  /* first glyph within data page   */
    0x4f0f,                                  /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_2_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_3                    /* next font page                 */
};

static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_20[1] =
{
    0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_21[11] =
{
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x00, 0x00, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_22[3] =
{
    0xa0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_23[10] =
{
    0x0a, 0x12, 0x12, 0x7f, 0x14, 0x14, 0xff, 0x24, 0x24, 0x28
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_24[14] =
{
    0x20, 0x78, 0x60, 0xa0, 0xa0, 0x60, 0x20, 0x38, 0x24, 0x24, 0x28, 0xf8, 0x20, 
    0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_25[22] =
{
    0xf1, 0x00, 0x91, 0x00, 0x8a, 0x00, 0x92, 0x00, 0xf4, 0x00, 0x08, 0x00, 0x0b, 
    0x80, 0x12, 0x40, 0x14, 0x40, 0x24, 0x40, 0x43, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_26[22] =
{
    0x38, 0x00, 0x64, 0x00, 0x44, 0x00, 0x44, 0x00, 0x28, 0x00, 0x30, 0x80, 0xc8, 
    0x80, 0x85, 0x00, 0x83, 0x00, 0xc3, 0x00, 0x7c, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_27[3] =
{
    0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_28[13] =
{
    0x20, 0x40, 0x40, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x40, 0x40, 0x20

};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_29[13] =
{
    0x80, 0x40, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x40, 0x80

};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_2a[6] =
{
    0x20, 0x20, 0xf8, 0x20, 0x60, 0x90
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_2b[7] =
{
    0x20, 0x20, 0x20, 0xfc, 0x20, 0x20, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_2c[4] =
{
    0x40, 0x40, 0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_2d[1] =
{
    0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_2e[1] =
{
    0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_2f[13] =
{
    0x04, 0x08, 0x08, 0x10, 0x10, 0x10, 0x20, 0x20, 0x40, 0x40, 0x40, 0x80, 0x80

};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_30[11] =
{
    0x78, 0x48, 0x84, 0x84, 0x84, 0x84, 0x84, 0x84, 0x84, 0xc8, 0x70
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_31[11] =
{
    0x20, 0x60, 0xa0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_32[11] =
{
    0x78, 0x88, 0x04, 0x04, 0x08, 0x08, 0x30, 0x40, 0x80, 0x80, 0xfc
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_33[11] =
{
    0xf0, 0x08, 0x08, 0x08, 0x08, 0x70, 0x08, 0x04, 0x04, 0x08, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_34[11] =
{
    0x04, 0x04, 0x0c, 0x14, 0x24, 0x24, 0x44, 0xff, 0x04, 0x04, 0x04
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_35[11] =
{
    0x78, 0x40, 0x80, 0x80, 0x70, 0x08, 0x04, 0x04, 0x04, 0x08, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_36[11] =
{
    0x3c, 0x40, 0x80, 0x80, 0xb8, 0xc4, 0x84, 0x84, 0x84, 0x44, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_37[11] =
{
    0xfc, 0x04, 0x08, 0x08, 0x10, 0x10, 0x20, 0x20, 0x20, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_38[11] =
{
    0x78, 0xc8, 0x84, 0x84, 0x48, 0x70, 0x8c, 0x84, 0x84, 0x84, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_39[11] =
{
    0x78, 0x88, 0x84, 0x84, 0x84, 0x8c, 0x74, 0x04, 0x08, 0x08, 0xf0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_3a[8] =
{
    0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_3b[10] =
{
    0x40, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x40, 0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_3c[7] =
{
    0x04, 0x18, 0x20, 0xc0, 0x60, 0x18, 0x04
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_3d[4] =
{
    0xfc, 0x00, 0x00, 0xfc
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_3e[7] =
{
    0x80, 0x60, 0x10, 0x0c, 0x18, 0x60, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_3f[11] =
{
    0x70, 0x88, 0x08, 0x08, 0x10, 0x20, 0x40, 0x40, 0x00, 0x00, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_40[24] =
{
    0x0f, 0x80, 0x30, 0x60, 0x40, 0x20, 0x4e, 0x90, 0x89, 0x10, 0x91, 0x10, 0x91, 
    0x10, 0x91, 0x30, 0x4e, 0xe0, 0x40, 0x00, 0x30, 0x00, 0x1f, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_41[22] =
{
    0x08, 0x00, 0x0c, 0x00, 0x14, 0x00, 0x14, 0x00, 0x12, 0x00, 0x22, 0x00, 0x21, 
    0x00, 0x3f, 0x00, 0x41, 0x00, 0x40, 0x80, 0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_42[11] =
{
    0xf8, 0x84, 0x84, 0x84, 0x88, 0xf8, 0x84, 0x84, 0x84, 0x84, 0xf8
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_43[11] =
{
    0x1e, 0x60, 0x40, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x60, 0x3e
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_44[11] =
{
    0xfc, 0x82, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x86, 0xf8
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_45[11] =
{
    0xf8, 0x80, 0x80, 0x80, 0x80, 0xf8, 0x80, 0x80, 0x80, 0x80, 0xfc
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_46[11] =
{
    0xf8, 0x80, 0x80, 0x80, 0x80, 0xf8, 0x80, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_47[11] =
{
    0x1e, 0x61, 0x40, 0x80, 0x80, 0x80, 0x87, 0x81, 0x81, 0x61, 0x3e
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_48[11] =
{
    0x81, 0x81, 0x81, 0x81, 0x81, 0xff, 0x81, 0x81, 0x81, 0x81, 0x81
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_49[11] =
{
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_4a[11] =
{
    0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x20, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_4b[11] =
{
    0x84, 0x88, 0x90, 0xb0, 0xa0, 0xc0, 0xa0, 0xb0, 0x98, 0x88, 0x84
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_4c[11] =
{
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0xf8
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_4d[22] =
{
    0x80, 0x40, 0xc0, 0x40, 0xc0, 0xc0, 0xa0, 0xc0, 0xa1, 0x40, 0x91, 0x40, 0x91, 
    0x40, 0x92, 0x40, 0x8a, 0x40, 0x84, 0x40, 0x84, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_4e[11] =
{
    0x81, 0xc1, 0xa1, 0xa1, 0x91, 0x89, 0x85, 0x85, 0x83, 0x81, 0x81
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_4f[22] =
{
    0x1e, 0x00, 0x61, 0x00, 0x40, 0x80, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 
    0x40, 0x80, 0x40, 0x80, 0x80, 0x61, 0x00, 0x3e, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_50[11] =
{
    0xf8, 0x84, 0x84, 0x84, 0x84, 0x84, 0xf8, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_51[24] =
{
    0x1e, 0x00, 0x61, 0x00, 0x40, 0x80, 0x80, 0x40, 0x80, 0x40, 0x80, 0x40, 0x80, 
    0x40, 0x80, 0x40, 0x80, 0x80, 0x61, 0x00, 0x3f, 0x00, 0x00, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_52[11] =
{
    0xf8, 0x84, 0x84, 0x84, 0x84, 0xf8, 0x88, 0x88, 0x84, 0x84, 0x84
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_53[11] =
{
    0x78, 0x80, 0x80, 0x80, 0x40, 0x30, 0x08, 0x04, 0x04, 0x08, 0x70
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_54[11] =
{
    0xfe, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_55[11] =
{
    0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x81, 0x82, 0x42, 0x3c
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_56[22] =
{
    0x80, 0x80, 0x41, 0x00, 0x41, 0x00, 0x41, 0x00, 0x22, 0x00, 0x22, 0x00, 0x22, 
    0x00, 0x14, 0x00, 0x14, 0x00, 0x18, 0x00, 0x08, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_57[22] =
{
    0x82, 0x08, 0x43, 0x08, 0x43, 0x08, 0x43, 0x10, 0x25, 0x10, 0x24, 0x90, 0x24, 
    0xa0, 0x28, 0xa0, 0x18, 0x60, 0x18, 0x40, 0x10, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_58[11] =
{
    0x41, 0x42, 0x22, 0x14, 0x18, 0x08, 0x18, 0x24, 0x22, 0x42, 0x41
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_59[11] =
{
    0x41, 0x42, 0x22, 0x24, 0x24, 0x18, 0x08, 0x08, 0x08, 0x08, 0x08
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5a[11] =
{
    0x7f, 0x02, 0x02, 0x04, 0x08, 0x08, 0x10, 0x20, 0x20, 0x40, 0xff
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5b[13] =
{
    0xc0, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0xc0

};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5c[12] =
{
    0x80, 0x80, 0x40, 0x40, 0x20, 0x20, 0x20, 0x10, 0x10, 0x08, 0x08, 0x04
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5d[13] =
{
    0xe0, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0xe0

};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5e[6] =
{
    0x20, 0x30, 0x50, 0x48, 0x88, 0x84
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_5f[1] =
{
    0xfc
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_60[2] =
{
    0x80, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_61[8] =
{
    0x78, 0x88, 0x08, 0x38, 0xc8, 0x88, 0x88, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_62[11] =
{
    0x80, 0x80, 0x80, 0xb8, 0xc4, 0x82, 0x82, 0x82, 0x82, 0xc4, 0xb8
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_63[8] =
{
    0x38, 0xc0, 0x80, 0x80, 0x80, 0x80, 0x80, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_64[11] =
{
    0x04, 0x04, 0x04, 0x7c, 0xc4, 0x84, 0x84, 0x84, 0x84, 0x84, 0x7c
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_65[8] =
{
    0x78, 0x84, 0x84, 0xfc, 0x80, 0x80, 0x84, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_66[11] =
{
    0x38, 0x20, 0x40, 0xf0, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_67[11] =
{
    0x7c, 0xc4, 0x84, 0x84, 0x84, 0x84, 0x84, 0x7c, 0x04, 0x84, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_68[11] =
{
    0x80, 0x80, 0x80, 0xb8, 0xc4, 0x84, 0x84, 0x84, 0x84, 0x84, 0x84
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_69[11] =
{
    0x80, 0x00, 0x00, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6a[14] =
{
    0x10, 0x00, 0x00, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 0x10, 
    0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6b[11] =
{
    0x80, 0x80, 0x80, 0x88, 0x90, 0xa0, 0xc0, 0xc0, 0xa0, 0x90, 0x88
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6c[11] =
{
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6d[16] =
{
    0xbb, 0x80, 0xca, 0x40, 0x84, 0x40, 0x84, 0x40, 0x84, 0x40, 0x84, 0x40, 0x84, 
    0x40, 0x84, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6e[8] =
{
    0xb8, 0xc4, 0x84, 0x84, 0x84, 0x84, 0x84, 0x84
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_6f[8] =
{
    0x78, 0xc4, 0x82, 0x82, 0x82, 0x82, 0xc4, 0x78
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_70[11] =
{
    0xb8, 0xc4, 0x82, 0x82, 0x82, 0x82, 0xc4, 0xb8, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_71[11] =
{
    0x7c, 0xc4, 0x84, 0x84, 0x84, 0x84, 0x84, 0x7c, 0x04, 0x04, 0x04
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_72[8] =
{
    0xb0, 0xc0, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_73[8] =
{
    0x70, 0x80, 0x80, 0xc0, 0x30, 0x10, 0x10, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_74[10] =
{
    0x40, 0x40, 0xf0, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x30
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_75[8] =
{
    0x84, 0x84, 0x84, 0x84, 0x84, 0x84, 0x8c, 0x74
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_76[8] =
{
    0x82, 0x44, 0x44, 0x44, 0x28, 0x28, 0x30, 0x10
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_77[16] =
{
    0x84, 0x40, 0x44, 0x40, 0x4c, 0x80, 0x4a, 0x80, 0x52, 0x80, 0x32, 0x80, 0x31, 
    0x00, 0x21, 0x00
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_78[8] =
{
    0x84, 0x48, 0x28, 0x30, 0x10, 0x28, 0x48, 0x84
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_79[11] =
{
    0x82, 0x44, 0x44, 0x48, 0x28, 0x28, 0x10, 0x10, 0x20, 0x20, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_7a[8] =
{
    0x7e, 0x04, 0x08, 0x10, 0x10, 0x20, 0x40, 0xfc
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_7b[13] =
{
    0x60, 0x40, 0x40, 0x40, 0x40, 0x80, 0x80, 0x80, 0x40, 0x40, 0x40, 0x40, 0x60

};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_7c[15] =
{
    0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 
    0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_7d[13] =
{
    0x80, 0x80, 0x40, 0x40, 0x40, 0x40, 0x20, 0x40, 0x40, 0x40, 0x40, 0x80, 0x80

};
static GX_CONST GX_UBYTE FONT_THEME_1_YaHei_char_7e[2] =
{
    0xe4, 0x98
};
static GX_CONST GX_GLYPH THEME_1_YaHei_FONT_PAGE_1_GLYPHS[95] =
{
    {FONT_THEME_1_YaHei_char_20, 0, 0, 4, 0, 1, 1},
    {FONT_THEME_1_YaHei_char_21, 11, 0, 4, 1, 1, 11},
    {FONT_THEME_1_YaHei_char_22, 11, -8, 5, 1, 3, 3},
    {FONT_THEME_1_YaHei_char_23, 11, -1, 9, 0, 8, 10},
    {FONT_THEME_1_YaHei_char_24, 12, 2, 8, 1, 6, 14},
    {FONT_THEME_1_YaHei_char_25, 11, 0, 12, 0, 10, 11},
    {FONT_THEME_1_YaHei_char_26, 11, 1, 11, 1, 9, 11},
    {FONT_THEME_1_YaHei_char_27, 11, -8, 3, 1, 1, 3},
    {FONT_THEME_1_YaHei_char_28, 11, 2, 4, 1, 3, 13},
    {FONT_THEME_1_YaHei_char_29, 11, 2, 4, 0, 3, 13},
    {FONT_THEME_1_YaHei_char_2a, 11, -5, 6, 0, 5, 6},
    {FONT_THEME_1_YaHei_char_2b, 8, -1, 10, 1, 6, 7},
    {FONT_THEME_1_YaHei_char_2c, 2, 2, 3, 0, 2, 4},
    {FONT_THEME_1_YaHei_char_2d, 5, -4, 6, 1, 4, 1},
    {FONT_THEME_1_YaHei_char_2e, 1, 0, 3, 1, 1, 1},
    {FONT_THEME_1_YaHei_char_2f, 11, 2, 6, -1, 6, 13},
    {FONT_THEME_1_YaHei_char_30, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_31, 11, 0, 5, 0, 3, 11},
    {FONT_THEME_1_YaHei_char_32, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_33, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_34, 11, 0, 8, 0, 8, 11},
    {FONT_THEME_1_YaHei_char_35, 11, 0, 8, 1, 6, 11},
    {FONT_THEME_1_YaHei_char_36, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_37, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_38, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_39, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_3a, 8, 0, 3, 1, 1, 8},
    {FONT_THEME_1_YaHei_char_3b, 8, 2, 3, 0, 2, 10},
    {FONT_THEME_1_YaHei_char_3c, 8, -1, 10, 1, 6, 7},
    {FONT_THEME_1_YaHei_char_3d, 6, -2, 10, 1, 6, 4},
    {FONT_THEME_1_YaHei_char_3e, 8, -1, 10, 1, 6, 7},
    {FONT_THEME_1_YaHei_char_3f, 11, 0, 7, 0, 5, 11},
    {FONT_THEME_1_YaHei_char_40, 11, 1, 14, 1, 12, 12},
    {FONT_THEME_1_YaHei_char_41, 11, 0, 10, 0, 9, 11},
    {FONT_THEME_1_YaHei_char_42, 11, 0, 8, 1, 6, 11},
    {FONT_THEME_1_YaHei_char_43, 11, 0, 9, 0, 7, 11},
    {FONT_THEME_1_YaHei_char_44, 11, 0, 10, 1, 8, 11},
    {FONT_THEME_1_YaHei_char_45, 11, 0, 8, 1, 6, 11},
    {FONT_THEME_1_YaHei_char_46, 11, 0, 7, 1, 5, 11},
    {FONT_THEME_1_YaHei_char_47, 11, 0, 10, 0, 8, 11},
    {FONT_THEME_1_YaHei_char_48, 11, 0, 10, 1, 8, 11},
    {FONT_THEME_1_YaHei_char_49, 11, 0, 3, 1, 1, 11},
    {FONT_THEME_1_YaHei_char_4a, 11, 0, 5, 0, 4, 11},
    {FONT_THEME_1_YaHei_char_4b, 11, 0, 8, 1, 7, 11},
    {FONT_THEME_1_YaHei_char_4c, 11, 0, 7, 1, 5, 11},
    {FONT_THEME_1_YaHei_char_4d, 11, 0, 13, 1, 10, 11},
    {FONT_THEME_1_YaHei_char_4e, 11, 0, 11, 1, 8, 11},
    {FONT_THEME_1_YaHei_char_4f, 11, 0, 12, 0, 10, 11},
    {FONT_THEME_1_YaHei_char_50, 11, 0, 8, 1, 6, 11},
    {FONT_THEME_1_YaHei_char_51, 11, 1, 11, 0, 10, 12},
    {FONT_THEME_1_YaHei_char_52, 11, 0, 8, 1, 7, 11},
    {FONT_THEME_1_YaHei_char_53, 11, 0, 8, 1, 6, 11},
    {FONT_THEME_1_YaHei_char_54, 11, 0, 8, 0, 7, 11},
    {FONT_THEME_1_YaHei_char_55, 11, 0, 10, 1, 8, 11},
    {FONT_THEME_1_YaHei_char_56, 11, 0, 9, 0, 9, 11},
    {FONT_THEME_1_YaHei_char_57, 11, 0, 14, 0, 13, 11},
    {FONT_THEME_1_YaHei_char_58, 11, 0, 9, 0, 8, 11},
    {FONT_THEME_1_YaHei_char_59, 11, 0, 8, 0, 8, 11},
    {FONT_THEME_1_YaHei_char_5a, 11, 0, 9, 0, 8, 11},
    {FONT_THEME_1_YaHei_char_5b, 11, 2, 4, 1, 2, 13},
    {FONT_THEME_1_YaHei_char_5c, 11, 1, 6, -1, 6, 12},
    {FONT_THEME_1_YaHei_char_5d, 11, 2, 4, 0, 3, 13},
    {FONT_THEME_1_YaHei_char_5e, 11, -5, 10, 1, 6, 6},
    {FONT_THEME_1_YaHei_char_5f, -3, 4, 6, 0, 6, 1},
    {FONT_THEME_1_YaHei_char_60, 11, -9, 4, 0, 2, 2},
    {FONT_THEME_1_YaHei_char_61, 8, 0, 7, 0, 5, 8},
    {FONT_THEME_1_YaHei_char_62, 11, 0, 8, 1, 7, 11},
    {FONT_THEME_1_YaHei_char_63, 8, 0, 7, 0, 5, 8},
    {FONT_THEME_1_YaHei_char_64, 11, 0, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_65, 8, 0, 8, 0, 6, 8},
    {FONT_THEME_1_YaHei_char_66, 11, 0, 4, 0, 5, 11},
    {FONT_THEME_1_YaHei_char_67, 8, 3, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_68, 11, 0, 8, 1, 6, 11},
    {FONT_THEME_1_YaHei_char_69, 11, 0, 3, 0, 1, 11},
    {FONT_THEME_1_YaHei_char_6a, 11, 3, 3, -2, 4, 14},
    {FONT_THEME_1_YaHei_char_6b, 11, 0, 7, 1, 6, 11},
    {FONT_THEME_1_YaHei_char_6c, 11, 0, 3, 1, 1, 11},
    {FONT_THEME_1_YaHei_char_6d, 8, 0, 12, 1, 10, 8},
    {FONT_THEME_1_YaHei_char_6e, 8, 0, 8, 1, 6, 8},
    {FONT_THEME_1_YaHei_char_6f, 8, 0, 8, 0, 7, 8},
    {FONT_THEME_1_YaHei_char_70, 8, 3, 8, 1, 7, 11},
    {FONT_THEME_1_YaHei_char_71, 8, 3, 8, 0, 6, 11},
    {FONT_THEME_1_YaHei_char_72, 8, 0, 5, 1, 4, 8},
    {FONT_THEME_1_YaHei_char_73, 8, 0, 6, 0, 4, 8},
    {FONT_THEME_1_YaHei_char_74, 10, 0, 4, 0, 4, 10},
    {FONT_THEME_1_YaHei_char_75, 8, 0, 8, 1, 6, 8},
    {FONT_THEME_1_YaHei_char_76, 8, 0, 7, 0, 7, 8},
    {FONT_THEME_1_YaHei_char_77, 8, 0, 10, 0, 10, 8},
    {FONT_THEME_1_YaHei_char_78, 8, 0, 6, 0, 6, 8},
    {FONT_THEME_1_YaHei_char_79, 8, 3, 7, 0, 7, 11},
    {FONT_THEME_1_YaHei_char_7a, 8, 0, 7, 0, 7, 8},
    {FONT_THEME_1_YaHei_char_7b, 11, 2, 4, 0, 3, 13},
    {FONT_THEME_1_YaHei_char_7c, 12, 3, 3, 1, 1, 15},
    {FONT_THEME_1_YaHei_char_7d, 11, 2, 4, 0, 3, 13},
    {FONT_THEME_1_YaHei_char_7e, 5, -3, 10, 1, 6, 2}
};

static GX_CONST GX_FONT THEME_1_YaHei = 
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    16,                                      /* font data height               */
    12,                                      /* font baseline offset           */
    0x20,                                    /* first glyph within data page   */
    0x7e,                                    /* last glyph within data page    */
    {THEME_1_YaHei_FONT_PAGE_1_GLYPHS},      /* pointer to glyph data          */
    &THEME_1_YaHei_PAGE_2                    /* next font page                 */
};


/* Font Table                                                                  */


extern GX_CONST GX_FONT _gx_system_font_mono;
GX_CONST GX_FONT *display_1_theme_1_font_table[] =
{
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &THEME_1_tips,
    &THEME_1_YaHei
};

/* Pixelmap data definitions                                                   */


/* THEME_1_RADIO_ON pixelmap data                                              */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_RADIO_ON_pixelmap_data[64] =
{
    0x00, 0xf5, 0x5c, 0x00, 0x03, 0x7f, 0xfd, 0xc0, 0x0f, 0xfd, 0x7f, 0x70, 0x3f, 
    0xd5, 0x57, 0xdc, 0x1f, 0x55, 0x55, 0xf4, 0xfd, 0x55, 0x55, 0x7f, 0x7d, 0x55, 
    0x55, 0x7f, 0x75, 0x55, 0x55, 0x5d, 0x75, 0x55, 0x55, 0x5d, 0x7d, 0x55, 0x55, 
    0x5f, 0xfd, 0x55, 0x55, 0x7f, 0x1f, 0x55, 0x55, 0xf4, 0x3f, 0xd5, 0x57, 0xdc, 
    0x0f, 0xfd, 0x7f, 0x70, 0x03, 0x7f, 0xfd, 0xc0, 0x00, 0x35, 0x5c, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_RADIO_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_TRANSPARENT,                 /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_RADIO_ON_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_RADIO_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_RADIO_OFF pixelmap data                                             */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_RADIO_OFF_pixelmap_data[64] =
{
    0x00, 0xd5, 0x54, 0x00, 0x01, 0x55, 0x55, 0x00, 0x05, 0x5f, 0xf5, 0x50, 0x15, 
    0xff, 0xff, 0x50, 0x17, 0xff, 0xff, 0xd4, 0x57, 0xff, 0xff, 0xd5, 0x5f, 0xff, 
    0xff, 0xf5, 0x5f, 0xff, 0xff, 0xf5, 0x5f, 0xff, 0xff, 0xf5, 0x5f, 0xff, 0xff, 
    0xf5, 0x57, 0xff, 0xff, 0xd5, 0x17, 0xff, 0xff, 0xd4, 0x15, 0xff, 0xff, 0x50, 
    0x05, 0x5f, 0xf5, 0x50, 0x01, 0x55, 0x55, 0xc0, 0x00, 0x15, 0x54, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_RADIO_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_TRANSPARENT,                 /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_RADIO_OFF_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_RADIO_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_ON pixelmap data                                           */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap_data[32] =
{
    0x00, 0x00, 0x7f, 0xfc, 0x7f, 0xfe, 0x7f, 0xfe, 0x7f, 0xee, 0x7f, 0xce, 0x77, 
    0x8e, 0x73, 0x1e, 0x72, 0x1e, 0x70, 0x3e, 0x78, 0x7c, 0x7d, 0xfc, 0x7f, 0xfc, 
    0x7f, 0xfe, 0x3f, 0xc4, 0x00, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    0,                                       /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_OFF pixelmap data                                          */

static GX_CONST GX_UBYTE DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap_data[32] =
{
    0x00, 0x00, 0x7f, 0xfc, 0x7f, 0xfe, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 
    0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 
    0x7f, 0xfc, 0x20, 0x00, 0x00, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    0,                                       /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap_data,
    sizeof(DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* Pixelmap Table                                                              */


GX_CONST GX_PIXELMAP *display_1_theme_1_pixelmap_table[] =
{
    GX_NULL,
    &DISPLAY_1_THEME_1_RADIO_ON_pixelmap,
    &DISPLAY_1_THEME_1_RADIO_OFF_pixelmap,
    &DISPLAY_1_THEME_1_CHECKBOX_ON_pixelmap,
    &DISPLAY_1_THEME_1_CHECKBOX_OFF_pixelmap
};

/* String values                                                               */

GX_CONST GX_UBYTE display_1_IN_PROMPT_Chinese[] = "in:";
GX_CONST GX_UBYTE display_1_STRING_1_Chinese[] = "prompt";
GX_CONST GX_UBYTE display_1_STRING_2_Chinese[] = "15.21";
GX_CONST GX_UBYTE display_1_STRING_3_Chinese[] = "mA";
GX_CONST GX_UBYTE display_1_STRING_4_Chinese[] = "V";
GX_CONST GX_UBYTE display_1_STRING_5_Chinese[] = "out:";
GX_CONST GX_UBYTE display_1_STRING_6_Chinese[] = "10.24";
GX_CONST GX_UBYTE display_1_STRING_7_Chinese[] = "v";
GX_CONST GX_UBYTE display_1_STRING_8_Chinese[] = "cur:";
GX_CONST GX_UBYTE display_1_STRING_9_Chinese[] = "10.321";
GX_CONST GX_UBYTE display_1_STRING_10_Chinese[] = "15.210";
GX_CONST GX_UBYTE display_1_STRING_11_Chinese[] = "10.240";
GX_CONST GX_UBYTE display_1_STRING_12_Chinese[] = "1234";
GX_CONST GX_UBYTE display_1_STRING_13_Chinese[] = {0xe8, 0xbe, 0x93, 0xe5, 0x85, 0xa5, 0x00};
GX_CONST GX_UBYTE display_1_STRING_14_Chinese[] = {0xe8, 0xbe, 0x93, 0xe5, 0x87, 0xba, 0x00};
GX_CONST GX_UBYTE display_1_STRING_15_Chinese[] = {0xe7, 0x94, 0xb5, 0xe6, 0xb5, 0x81, 0x00};
GX_CONST GX_UBYTE display_1_STRING_16_Chinese[] = {0xe4, 0xbc, 0x8f, 0x00};
GX_CONST GX_UBYTE display_1_STRING_17_Chinese[] = "00.000";
GX_CONST GX_UBYTE display_1_STRING_18_Chinese[] = {0xe8, 0xae, 0xbe, 0xe7, 0xbd, 0xae, 0xe7, 0x94, 0xb5, 0xe6, 0xb5, 0x81, 0x00};
GX_CONST GX_UBYTE display_1_STRING_19_Chinese[] = "A";
GX_CONST GX_UBYTE display_1_STRING_20_Chinese[] = {0xe8, 0xae, 0xbe, 0xe7, 0xbd, 0xae, 0xe6, 0x9c, 0x80, 0xe5, 0xa4, 0xa7, 0xe7, 0x94, 0xb5, 0xe6, 0xb5, 0x81, 0x00};
GX_CONST GX_UBYTE display_1_STRING_21_Chinese[] = {0xe8, 0xae, 0xbe, 0xe7, 0xbd, 0xae, 0xe8, 0xbe, 0x93, 0xe5, 0x87, 0xba, 0xe7, 0x94, 0xb5, 0xe5, 0x8e, 0x8b, 0x00};

/* String Table for display_1 language Chinese                                 */

GX_CONST GX_STRING display_1_Chinese_string_table[23] =
{
    {GX_NULL, 0},
    {(GX_CONST GX_CHAR *)display_1_IN_PROMPT_Chinese, sizeof(display_1_IN_PROMPT_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_1_Chinese, sizeof(display_1_STRING_1_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_2_Chinese, sizeof(display_1_STRING_2_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_3_Chinese, sizeof(display_1_STRING_3_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_4_Chinese, sizeof(display_1_STRING_4_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_5_Chinese, sizeof(display_1_STRING_5_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_6_Chinese, sizeof(display_1_STRING_6_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_7_Chinese, sizeof(display_1_STRING_7_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_8_Chinese, sizeof(display_1_STRING_8_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_9_Chinese, sizeof(display_1_STRING_9_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_10_Chinese, sizeof(display_1_STRING_10_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_11_Chinese, sizeof(display_1_STRING_11_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_12_Chinese, sizeof(display_1_STRING_12_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_13_Chinese, sizeof(display_1_STRING_13_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_14_Chinese, sizeof(display_1_STRING_14_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_15_Chinese, sizeof(display_1_STRING_15_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_16_Chinese, sizeof(display_1_STRING_16_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_17_Chinese, sizeof(display_1_STRING_17_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_18_Chinese, sizeof(display_1_STRING_18_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_19_Chinese, sizeof(display_1_STRING_19_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_20_Chinese, sizeof(display_1_STRING_20_Chinese) - 1},
    {(GX_CONST GX_CHAR *)display_1_STRING_21_Chinese, sizeof(display_1_STRING_21_Chinese) - 1}
};

/*  Language Table                                                             */


GX_CONST GX_STRING *display_1_language_table[1] = 
{
    display_1_Chinese_string_table,
};

GX_THEME display_1_theme_1 =
{
    (GX_COLOR *) display_1_theme_1_color_table,
    (GX_FONT **) display_1_theme_1_font_table,
    (GX_PIXELMAP **) display_1_theme_1_pixelmap_table,
    NULL,
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_CANVAS,                  /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_VERTICAL,
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_HORIZONTAL,
    29,                                      /* color table size               */
    6,                                       /* font table size                */
    5,                                       /* pixelmap table size            */
    0                                        /* palette size                   */

};
GX_CONST GX_THEME *display_1_theme_table[1] =
{
    &display_1_theme_1
};

